app = "backend-tourly"
primary_region = "cdg"

[env]
  GIN_MODE = "release"

[mounts]
  source = "data"
  destination = "/pb/data"

[deploy]
  release_command = "your-release-command"

[services]
  [[services.http]]
    internal_port = 8090
    force_https = true
    [[services.http.routes]]
      prefix = "/"
      continue = true